<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403081321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bus_serving (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bus_id INT NOT NULL, line_id INT NOT NULL, stop_id INT NOT NULL, direction_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1126947E2546731D ON bus_serving (bus_id)');
        $this->addSql('CREATE INDEX IDX_1126947E4D7B7542 ON bus_serving (line_id)');
        $this->addSql('CREATE INDEX IDX_1126947E3902063D ON bus_serving (stop_id)');
        $this->addSql('CREATE INDEX IDX_1126947EAF73D997 ON bus_serving (direction_id)');
        $this->addSql('CREATE UNIQUE INDEX bus_serving_line_stop_dir_unique ON bus_serving (line_id, stop_id, direction_id)');
        $this->addSql('CREATE TABLE transit_direction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, label VARCHAR(255) NOT NULL, line_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5674B5A34D7B7542 ON transit_direction (line_id)');
        $this->addSql('CREATE UNIQUE INDEX transit_direction_line_code ON transit_direction (line_id, code)');
        $this->addSql('CREATE TABLE transit_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX transit_line_code_unique ON transit_line (code)');
        $this->addSql('CREATE TABLE transit_stop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX transit_stop_code_unique ON transit_stop (code)');
        $this->addSql('ALTER TABLE bus_serving ADD CONSTRAINT FK_1126947E2546731D FOREIGN KEY (bus_id) REFERENCES bus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bus_serving ADD CONSTRAINT FK_1126947E4D7B7542 FOREIGN KEY (line_id) REFERENCES transit_line (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bus_serving ADD CONSTRAINT FK_1126947E3902063D FOREIGN KEY (stop_id) REFERENCES transit_stop (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bus_serving ADD CONSTRAINT FK_1126947EAF73D997 FOREIGN KEY (direction_id) REFERENCES transit_direction (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transit_direction ADD CONSTRAINT FK_5674B5A34D7B7542 FOREIGN KEY (line_id) REFERENCES transit_line (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bus_serving DROP CONSTRAINT FK_1126947E2546731D');
        $this->addSql('ALTER TABLE bus_serving DROP CONSTRAINT FK_1126947E4D7B7542');
        $this->addSql('ALTER TABLE bus_serving DROP CONSTRAINT FK_1126947E3902063D');
        $this->addSql('ALTER TABLE bus_serving DROP CONSTRAINT FK_1126947EAF73D997');
        $this->addSql('ALTER TABLE transit_direction DROP CONSTRAINT FK_5674B5A34D7B7542');
        $this->addSql('DROP TABLE bus_serving');
        $this->addSql('DROP TABLE transit_direction');
        $this->addSql('DROP TABLE transit_line');
        $this->addSql('DROP TABLE transit_stop');
    }
}
