<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402084525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP INDEX idx_report_gravite');
        $this->addSql('DROP INDEX idx_report_statut');
        $this->addSql('DROP INDEX idx_report_matricule');
        $this->addSql('DROP INDEX idx_report_driver_date');
        $this->addSql('ALTER TABLE report DROP matricule');
        $this->addSql('ALTER TABLE report DROP gravite');
        $this->addSql('ALTER TABLE report DROP score_ia');
        $this->addSql('ALTER TABLE report DROP type_fait');
        $this->addSql('ALTER TABLE report DROP contexte_attenuant');
        $this->addSql('ALTER TABLE report DROP raison_contexte');
        $this->addSql('ALTER TABLE report DROP recommandation_ia');
        $this->addSql('ALTER TABLE report DROP meteo_contexte');
        $this->addSql('ALTER TABLE report DROP heure_pointe');
        $this->addSql('ALTER TABLE report DROP courrier_genere');
        $this->addSql('ALTER TABLE report DROP statut_traitement');
        $this->addSql('ALTER TABLE report DROP nb_signalements_historique');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE report ADD matricule VARCHAR(50) DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD gravite VARCHAR(10) DEFAULT \'moyen\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD score_ia INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE report ADD type_fait VARCHAR(255) DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD contexte_attenuant BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE report ADD raison_contexte TEXT DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD recommandation_ia TEXT DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD meteo_contexte VARCHAR(255) DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD heure_pointe BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE report ADD courrier_genere TEXT DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD statut_traitement VARCHAR(20) DEFAULT \'en_attente\' NOT NULL');
        $this->addSql('ALTER TABLE report ADD nb_signalements_historique INT DEFAULT 0 NOT NULL');
        $this->addSql('CREATE INDEX idx_report_gravite ON report (gravite)');
        $this->addSql('CREATE INDEX idx_report_statut ON report (statut_traitement)');
        $this->addSql('CREATE INDEX idx_report_matricule ON report (matricule)');
        $this->addSql('CREATE INDEX idx_report_driver_date ON report (driver_id, created_at)');
    }
}
