<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331092930 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE driver (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contact JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE report ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE report ADD report_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE report ADD reporter_contact JSONB NOT NULL');
        $this->addSql('ALTER TABLE report ADD driver_id INT NOT NULL');
        $this->addSql('ALTER TABLE report ADD bus_id INT NOT NULL');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784C3423909 FOREIGN KEY (driver_id) REFERENCES driver (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F77842546731D FOREIGN KEY (bus_id) REFERENCES bus (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C42F7784C3423909 ON report (driver_id)');
        $this->addSql('CREATE INDEX IDX_C42F77842546731D ON report (bus_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE driver');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784C3423909');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F77842546731D');
        $this->addSql('DROP INDEX IDX_C42F7784C3423909');
        $this->addSql('DROP INDEX IDX_C42F77842546731D');
        $this->addSql('ALTER TABLE report DROP created_at');
        $this->addSql('ALTER TABLE report DROP report_date');
        $this->addSql('ALTER TABLE report DROP reporter_contact');
        $this->addSql('ALTER TABLE report DROP driver_id');
        $this->addSql('ALTER TABLE report DROP bus_id');
    }
}
